version: '3'

services:
  frontend:
    build: ./react-frontend
    depends_on:
      - backend
  backend:
    build: ./flask-backend
    environment:
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
    depends_on:
      - db
    volumes:
      - ./flask-backend/app:/app
    ports:
      - 5000:5000

  db:
    image: postgres:10.2
